QUBEKit/dihedrals.py
QUBEKit/molecules/components.py
QUBEKit/molecules/ligand.py
QUBEKit/tests/ligand/ligand_test.py
QUBEKit/utils/file_handling.py
QUBEKit/virtual_sites.py
README.md

Rotatable bonds changed to use smirks patterns and removed refs to -geo in README

Rotatable Bonds and Virtual Sites Clean-up

---

qubekit/engines/base_engine.py
qubekit/engines/torsiondrive.py
qubekit/tests/engines/qcengine_test.py
qubekit/tests/ligand/parametrisation_test.py

This PR adds some more tests for improper torsions to make sure none are lost when round-tripping to file after parameterization. This extends the last test as the number of improper torsions is explicitly checked rather than the total energy as they may not contribute much when relaxed.

More Improper torsion tests.

---

qubekit/engines/torsiondrive.py
qubekit/molecules/components.py
qubekit/tests/engines/torsiondrive_test.py

This PR makes the scratch folders in the torsiondrive engine have a unique job id to ensure they are not shared between QM processes. The folders are now also removed once the torsiondrive is complete and a minimal number of files are saved which encode the whole torsiondrive.

TorsionDrive scratch fix

---

qubekit/forcefield/parameters.py
qubekit/tests/conftest.py
qubekit/tests/torsions/test_forcebalance.py
qubekit/tests/torsions/test_scan.py
qubekit/torsions/fitting/forcebalance_wrapper.py
qubekit/torsions/scanning/torsion_scanner.py

This PR allows qubekit to deduplicate torsion scans by torsion symmetry, this should lead to less torsion drives. Torsion symmetry is also used during fitting, here like torsions are linked together using parameter eval tags which should lead to faster fitting as the gradients of fewer parameters are required. The default fitting convergence criteria has also been relaxed slightly.

Torsion symmetry update.

---

qubekit/molecules/ligand.py

This PR updates the vsite default LJ parameters to be `sigma=1` `epsilon=0` to make sure long-range corrections work when using a custom nonbonded force in opemmm during alchemical calculations.

Vsite default LJ parameters

---

qubekit/parametrisation/base_parametrisation.py
qubekit/tests/ligand/parametrisation_test.py

All torsion values from the initial parameterisation are now saved, this fixes a bug where dummy values were dropped when trying to parameterise a molecule with missing coverage in the base force field.

Save all torsion values 

---

qubekit/cli/combine.py
qubekit/tests/cli/test_combine.py

This PR adds a new flag to the combined xmls CLI entry point which allows for no optimisation targets in the resulting combined XML file. This is useful for single point evaluations in ForceBalance!

Combine xmls with no targets

---

qubekit/cli/combine.py
qubekit/tests/cli/test_combine.py

This PR fixes the xml combiner CLI command to include the alpha and beta scaling when not fitting alpha and beta which was missed previously. This would cause the parameter eval tags to be incorrect and give inconsistent sigma and epsilon values compared to those calculated by qubekit directly.

Fix missing alpha and beta when combining xmls

---

qubekit/nonbonded/virtual_sites.py
qubekit/tests/conftest.py
qubekit/tests/non_bonded/virtual_sites_test.py

This PR adds a flag `freeze_site_angles` which controls if the angle between 2 virtual sites for the 2 sites 2 bonds case is to be optimised or not. For example 2 sites on alcohol currently have a fixed angle of 90 degrees with this flag set to `True` when set to `False` this optimises to around 111 degrees.  

Sites angle symmetry update

---

qubekit/nonbonded/virtual_sites.py
qubekit/tests/non_bonded/virtual_sites_test.py

This PR adds vsite-parent distance regularisation to the objective function using L1 regularisation.

Vsite distance regularisation

---

qubekit/cli/combine.py
qubekit/cli/utils.py
qubekit/tests/cli/test_combine.py
setup.py

This PR updates the offxml combine method to use a plugin which avoids the use of parameter eval statements. Here we assign each atom a volume via smirks and use a custom vdW handler with Rfree, alpha and beta global attributes which can be optimised with Forcebalance. We also add support for TIP3P water in the offxml. If parameters are not to be optimised a standard offxml is made using the default vdW handler.

Offxml plugin

---

qubekit/engines/qcengine.py
qubekit/engines/torsiondrive.py
qubekit/tests/engines/gaussian_harness_test.py
qubekit/tests/engines/torsiondrive_test.py
qubekit/tests/non_bonded/test_charges.py

This PR fixes the way the torsiondrive state file is saved and loaded locally to allow for restarts when the settings match between two runs. 

Fix checkpointing the torsiondrive state file

---

qubekit/engines/gaussian_harness.py

This PR aligns the qcvars name for the WBO matrix from gaussian with psi4, they are now stored under `WIBERG LOWDIN INDICES`

Fix WBO qcvars name for gaussian

---

qubekit/cli/utils.py

This PR fixes a potential issue where the qubekit plugin used for fitting would set charges to dummy values of 0 for everything if the parameter handlers were resolved with library charges before the plugin handler. This change should mean the correct charges are applied regardless of order.

Plugin charge fix

---

qubekit/cli/combine.py
qubekit/cli/utils.py
qubekit/cli/water_models.py
qubekit/tests/cli/test_combine.py

This PR fixes the local vsite plugin by making it incompatible with the standard vsite handler from openff, we also ensure sites are added to openmm systems and topology in the same order as the reference particles so they can be associated with the correct molecule.

fix plugin sites

---

qubekit/molecules/ligand.py
qubekit/molecules/utils.py
qubekit/tests/ligand/ligand_test.py
qubekit/tests/ligand/parametrisation_test.py

This PR fixes a bug in the valence type grouping method which used strings like `23-33` to build a bond type. The types were then clustered by checking the forward and reversed strings which would fail as the example bond type would become `33-32` and not be grouped correctly, tuples should avoid this issue.

Make symmetry codes ints and tuples

---

qubekit/bonded/qforce.py
qubekit/cli/combine.py
qubekit/cli/utils.py
qubekit/forcefield/__init__.py
qubekit/forcefield/force_groups.py
qubekit/forcefield/parameters.py
qubekit/molecules/ligand.py
qubekit/tests/bonded/qforce_test.py
qubekit/tests/cli/test_combine.py
qubekit/tests/ligand/ligand_test.py
qubekit/tests/ligand/parametrisation_test.py

This PR updates the old handling of Urey-Bradley terms from QForce to use a dedicated handler in QUBEKit. These are now exported to OpenMM via the AMOEBA plugin handler which means they can be loaded with no virtual bonds and will have the correct non-bonded exceptions.

Use the amoeba plugin handler for Urey-Bradley terms

---

qubekit/molecules/ligand.py
qubekit/tests/cli/test_combine.py

This PR changes the library charges SMIRKS generation to use Chemper to ensure the patterns are specific enough to stop the miss application of the charges. This was found to happen with basic SMARTS patterns during mixture fitting when two molecules are included in the offxml and one is a substructure of the other. 

Fix offxml library charges

---

devtools/conda-envs/everything.yaml

Matplotlib complains about pyparsing having the wrong version: "ImportError: Matplotlib requires pyparsing>=2.0.1"; you have 1.5.0. Pyparsing package has the right version, but there is a file pyparsing.py in the conda/bin which belongs to the pcmsolver=1.1.4 from the psi4 channel. The new one pcmsolver-1.2.1 resolves this issue.

Old PCMsolver overwrite the pyparsing package

---

devtools/conda-envs/basic.yaml
devtools/conda-envs/everything.yaml

Fix the CI by pinning the forcebalance version as the recipe allows for incompatible versions of the openff-toolkit-base.

Pin forcebalance in CI

---

qubekit/tests/workflow/test_workflow.py
qubekit/workflow/workflow.py

This PR fixes the running of workflows with optional stages. Fragmentation was introduced as an optional stage but only vsites were hardcoded as an optional stage meaning the workflow would error when ran with fragmentation as `None`. This is now fixed by checking each stage in the normal workflow and if that stage is `None` it is added to the skipped stages list. 

Fix optional stages

---

qubekit/cli/combine.py
qubekit/cli/utils.py

This PR fixes the units for the AIM volumes to be in bohr^3 as they should be. Currently, they are set as angstroms^3 and then requested in angstroms^3 so no conversion happens, this fix will break old offxml files with incorrect units. 

Volume unit fix

---

qubekit/cli/combine.py
qubekit/cli/utils.py
qubekit/nonbonded/lennard_jones.py
qubekit/tests/cli/test_combine.py
qubekit/tests/non_bonded/test_nonbonded.py

This PR changes when the alpha and beta scaling are applied during the LJ derivation stage to allow them to be applied to polar Hs before being transferred to the parent atoms. So a scaled C6 term is derived for each atom then C6 prime on the parent is calculated from these terms.
This also fixes a bug in the polar h transfer code where the transfer was missed in protocol 4a as it assumed the presence of a polar H Rfree term under the normal key `X` which is not needed. Tests have been added to capture this failure in future and the reference values have been calculated by hand using the data in the `methanol.json` model in the data folder.

Alpha and beta scaling with transfered polar H terms

---

qubekit/workflow/workflow.py

This PR updates the final outputs of a QUBEKit run to include an offxml with and without H-bond constraints (has `_unconstrained` suffix) and a pdb and sdf file of the molecule. Thus the final parameters can be used in OpenMM directly (pdb + XML) or via the openff-toolkit (sdf + offxml). 

Update finall outputs

---

qubekit/cli/combine.py
qubekit/molecules/ligand.py
qubekit/tests/ligand/parametrisation_test.py

This PR fixes an issue with fragment force fields which can have duplicate parameters when the smirks are made using `chemper ClusterGraph` and have to match every interaction instance (bonds, angles etc..) of the same type (symmetry equivalent). Now we use `SingleGraphs` built for a single instance of the interaction, these then transfer automatically to equivalent types of interactions.

Fragment force field fix

---

qubekit/molecules/ligand.py

This PR fixes a recent testing failure caused when checking for coordinates before converting the QUBEKit Ligand to qcschema. The issue is caused by comparing a numpy array with an empty list, as we use pydantic to enforce the types we will always have a numpy array or `None` so we can just check the shape of the array.

Fix coordinate check
