- QUBEKit/utils/helpers.py
Removed charge and torsion_order from bulk. Both are now inferred.
> updated bulk csv

- MANIFEST.in
This PR updates the manifest to remove references to the gui package and to include testing data and templates used in the new gaussian harness.
> Manifest fix

- QUBEKit/molecules/utils.py
This PR changes the conformer generation method used when starting from smiles to use basic rules and results in better starting conformers when tested on small molecules.
> Conformer Generation update.

- qubekit/virtual_sites.py
Minor fix to symmetric constraint in v-sites.
> Fixed symmetric constraint for two sites two bonds

- qubekit/engines/base_engine.py
Fixed resource validator for for splitting up workers.
> Fixed resource validator for for splitting up workers.

- qubekit/engines/gaussian_harness.py
- qubekit/tests/engines/gaussian_harness_test.py
This PR fixes the theory name converter for gaussian which can cause it to seg fault if it is incorrect. The test is also updated to make sure that convert is case insensitive.
> Gaussian theory name

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/everything.yaml
- qubekit/run.py
- qubekit/tests/run_test.py
This PR allows conformers that fail to be pre-optimised to pass to the next stage by using the last conformer in the trajectory as the starting point for the full `qm_optimise` stage.
> Pre opt update

- qubekit/molecules/ligand.py
- qubekit/tests/ligand/parametrisation_test.py
This PR adds the version and creation date to forcefield xmls wrote by qubekit.
> XML versioning

- qubekit/engines/torsiondrive.py
- qubekit/tests/engines/torsiondrive_test.py
This PR adds the option to pass seed conformers to torsiondrives, which would allow pre-optimised conformers to be used in future. The seed conformers are also written locally. 
This PR also reworks how many workers are set up during torsiondrives to split the resources more efficiently. Now the number of workers at each iteration of a torsiondrive will be `min([n_jobs, n_workers])` where `n_jobs` is the number of grid points to optimise and `n_workers` is the maximum number of allowed workers.  
> Torsiondrive seed conformers

- qubekit/nonbonded/lennard_jones.py
Updated rfree/alpha/beta extraction to allow multiple .out files; halogen extraction; and overall much safer param extraction.
> rfree extraction from ForceBalance

- qubekit/nonbonded/lennard_jones.py
This PR makes the alpha, beta and rfree parameters normal fields on the LJ class allowing them to be saved and loaded from config files.
> Add free parameters to configs

- qubekit/bonded/mod_seminario.py
- qubekit/bonded/qforce.py
- qubekit/charges/solvent_settings/psi.py
- qubekit/engines/openmm.py
- qubekit/nonbonded/lennard_jones.py
- qubekit/nonbonded/protocols.py
- qubekit/nonbonded/virtual_sites.py
- qubekit/tests/ligand/ligand_test.py
- qubekit/tests/non_bonded/test_charges.py
- qubekit/tests/non_bonded/virtual_sites_test.py
- qubekit/utils/constants.py
This PR adds the optimised HCNOS and halogen parameters for protocols 5b/d.
> update new 5b/d halogen parameters

- qubekit/bonded/mod_seminario.py
- qubekit/engines/gaussian_harness.py
- qubekit/nonbonded/virtual_sites.py
- qubekit/tests/ligand/parametrisation_test.py
This PR fixes the gradient parsing for Gaussian 16 output files.
> Fix g16 gradient parsing

- README.md
- devtools/conda-envs/basic.yaml
- devtools/conda-envs/everything.yaml
- qubekit/cli/combine.py
- qubekit/cli/water_models.py
- qubekit/tests/cli/test_combine.py
- qubekit/tests/engines/geometry_optimiser_test.py
- qubekit/torsions/fitting/forcebalance_wrapper.py
This PR adds the tip4p-fb water model as an option when creating a combined offxml from the CLI.
> Add tip4p-fb

- qubekit/engines/geometry_optimiser.py
- qubekit/engines/openmm.py
- qubekit/molecules/ligand.py
- qubekit/parametrisation/antechamber.py
- qubekit/parametrisation/base_parametrisation.py
- qubekit/parametrisation/gromacs.py
- qubekit/parametrisation/openff.py
- qubekit/parametrisation/xml.py
- qubekit/parametrisation/xml_protein.py
- qubekit/proteins/protein_tools.py
- qubekit/tests/ligand/ligand_test.py
- qubekit/tests/ligand/parametrisation_test.py
- qubekit/torsions/fitting/forcebalance_wrapper.py
- qubekit/workflow/helper_stages.py
This PR cleans up the warnings from qcengine by using the new `task_config` interface and fixes the openmm imports.
> Qcengine/ import cleanup

- .github/workflows/CI.yaml
This PR updates the testing environments to be python 3.8 & 3.9.
> test on 3.8 and 3.9

- qubekit/bonded/mod_seminario.py
- qubekit/molecules/ligand.py
- qubekit/tests/ligand/parametrisation_test.py
This PR fixes part of #335 by allowing the modified Seminario method to be run on linear molecules with no angles.
> Fix linear molecules 

- qubekit/nonbonded/virtual_sites.py
Update the v-site plots for the matplotlib 3.6 API.
> fix v-site plots

- qubekit/bonded/mod_seminario.py
- qubekit/cli/utils.py
- qubekit/data/ring_test.json
- qubekit/data/templates/optimize.txt
- qubekit/molecules/ligand.py
- qubekit/molecules/utils.py
- qubekit/parametrisation/openff.py
- qubekit/tests/conftest.py
- qubekit/tests/ligand/ligand_test.py
- qubekit/tests/ligand/parametrisation_test.py
- qubekit/tests/torsions/test_forcebalance.py
- qubekit/torsions/__init__.py
- qubekit/torsions/fitting/forcebalance_wrapper.py
- setup.py
First implementation of the openff-forcebalance torsion optimiser. 
> Openff forcebalance

- qubekit/fragmentation/wbo_fragmenter.py
- qubekit/tests/fragmentation/wbofragmenter_test.py
Repairing deduplication of fragments
> Presorting which is required by groupby to work.

- qubekit/nonbonded/lennard_jones.py
Remove the old FB Rfree extraction code as we now use config files for this data.
> Remove old rfree FB extraction code

- qubekit/fragmentation/wbo_fragmenter.py
- qubekit/workflow/workflow.py
This PR removes some old UB code calls from the workflow that are no longer needed.
> Remove old ub code

- .github/workflows/Lint.yaml
- .github/workflows/integration.yaml
- devtools/conda-envs/everything.yaml
- qubekit/__init__.py
- qubekit/data/integration_workflow.json
- qubekit/data/templates/optimize.txt
- qubekit/engines/torsiondrive.py
- qubekit/tests/torsions/test_forcebalance.py
- qubekit/torsions/fitting/forcebalance_wrapper.py
- qubekit/utils/datastructures.py
- qubekit/workflow/helper_stages.py
To avoid issues like #363 set up integration testing to run a fast full qubekit fit of ethanol to catch issues unit tests miss.
> Integration testing 

- devtools/conda-envs/basic.yaml
- devtools/conda-envs/everything.yaml
This PR updates the testing environments to work with openff-toolkit-0.10.7
> update to toolkit 10.7

- qubekit/molecules/ligand.py
- qubekit/tests/ligand/parametrisation_test.py
Make sure the UB force tags are only included when there are parameters else it is removed.
> UB force cleanup

- qubekit/cli/combine.py
- qubekit/cli/utils.py
- qubekit/molecules/ligand.py
- qubekit/tests/cli/test_combine.py
- qubekit/tests/cli/test_utils.py
This PR updates the offxml QUBEKit volume handler to use a single parameter per molecule, now the volumes are indexed and work the same way as library charges and simplify the resulting offxml files.
> Plugin volume update 

- qubekit/cli/progress.py
Fix the bulk run progress report to make sure the stages are reported in the same order as the headings 
> Progress fix
